
stages:
  - test # unit tests + lint
  - build # babel, node-sass etc.
  - package # .rpm, .deb, .dmg., .zip
  - deploy # github releases, bintray, AUR
  - notify # pushover

# Gitbook documentation
book:
  stage: test
  tags:
    - dropsy
  script:
    - release/ci-book.rb

# Unit tests
test:
  stage: test
  tags:
    - linux
  script:
    - release/ci-test.rb
  except:
    - tags

# JavaScript standard formatting
lint:
  stage: test
  tags:
    - linux
  script:
    - release/ci-lint.rb
  except:
    - tags

# compile javascript & scss using babel & node-sass
compile:
  stage: build
  tags:
    - linux
  script:
    - release/ci-build.rb
  only:
    - tags
  artifacts:
    paths:
      - stage.tar.gz

# generate .desktop file for Linux
generate-linux-extras:
  stage: build
  tags:
    - linux
  script:
    - release/ci-generate-linux-extras.rb
  only:
    - tags
  artifacts:
    paths:
      - linux-extras

# .tar.gz, .rpm and .deb
package:linux:386:
  stage: package
  tags:
    - linux
  script:
    - release/ci-package.rb linux 386
  only:
    - tags
  artifacts:
    paths:
      - build-artifacts

# .tar.gz, .rpm and .deb
package:linux:amd64:
  stage: package
  tags:
    - linux
  script:
    - release/ci-package.rb linux amd64
  only:
    - tags
  artifacts:
    paths:
      - build-artifacts

# .dmg and .zip
package:darwin:amd64:
  stage: package
  tags:
    - darwin
  script:
    - release/ci-package.rb darwin amd64
  only:
    - tags
  artifacts:
    paths:
      - build-artifacts

# TODO: roll out 64-bit releases
package:windows:386:
  stage: package
  tags:
    - windows
  only:
    - tags
  script:
    - release/ci-package.rb windows 386
  artifacts:
    paths:
      - build-artifacts

# ArchLinux user repository
package:aur:
  stage: package
  tags:
    - archlinux
  only:
    - tags
  script:
    - release/ci-deploy-aur.rb

# GitHub releases are used for Squirrel.Windows & Squirrel.Mac,
# along with direct downloads
deploy:github:
  stage: deploy
  tags:
    - linux
  only:
    - tags
  only:
    - tags
  script:
    - release/ci-deploy-github.rb

# We have a YUM (rpm) & APT (deb) repository on bintray
deploy:bintray:
  stage: deploy
  only:
    - tags
  tags:
    - linux
  script:
    - release/ci-deploy-bintray.rb

# Pushover
notify:
  stage: notify
  tags:
    - linux
  script:
    - release/ci-notify.sh
  only:
    - tags
