
cache:
  key: "$CI_BUILD_STAGE/$CI_BUILD_REF_NAME"
  untracked: true

stages:
  - test
  # - mkrelease
  # - deploy
  # - notify

book:
  stage: test
  tags:
    - dropsy
  script:
    - release/ci-book.rb

test:
  stage: test
  tags:
    - linux
  script:
    - release/ci-test.rb
  except:
    - tags

# mkrelease:
#   stage: mkrelease
#   tags:
#     - linux
#   script:
#     - release/ci-mkrelease.sh
#   only:
#     - tags
#
# deploy:linux:386:
#   stage: deploy
#   tags:
#     - linux
#   script:
#     - export CI_OS=linux
#     - export CI_ARCH=386
#     - release/ci-deploy.sh
#   only:
#     - tags
#
# deploy:linux:amd64:
#   stage: deploy
#   tags:
#     - linux
#   script:
#     - export CI_OS=linux
#     - export CI_ARCH=amd64
#     - release/ci-deploy.sh
#   only:
#     - tags
#
# deploy:darwin:amd64:
#   stage: deploy
#   tags:
#     - darwin
#   script:
#     - export CI_OS=darwin
#     - export CI_ARCH=amd64
#     - release/ci-deploy.sh
#   only:
#     - tags
#
# deploy:windows:386:
#   stage: deploy
#   tags:
#     - windows
#   script:
#     - export CI_OS=windows
#     - export CI_ARCH=386
#     - release/ci-deploy.sh
#   only:
#     - tags
#
# notify:
#   stage: notify
#   tags:
#     - linux
#   script:
#     - release/ci-notify.sh
#   only:
#     - tags
