
stages:
  - build
  - package
  - deploy

test-linux:
  stage: build
  tags:
    - linux
  script:
    - release/ci-test.js
  except:
    - tags
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - screenshots
      - chrome-driver.log.txt

test-darwin:
  stage: build
  tags:
    - darwin
  script:
    - release/ci-test.js
  except:
    - tags
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - screenshots
      - chrome-driver.log.txt

test-windows:
  stage: build
  tags:
    - windows
  script:
    - release/ci-test.js
  except:
    - tags
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - screenshots
      - chrome-driver.log.txt

# i18n check
i18n-check:
  stage: build
  tags:
    - linux
  script:
    - release/ci-i18n-check.js
  except:
    - tags

# Compile javascript & css
compile:
  stage: build
  tags:
    - linux
  script:
    - release/ci-compile.js
  only:
    - tags
  artifacts:
    expire_in: 1 week
    paths:
      - prefix.tar

# 32-bit linux portable builds
package-linux-386:
  stage: package
  tags:
    - linux
  script:
    - release/ci-package.js linux 386
  artifacts:
    expire_in: 1 week
    paths:
      - packages
  dependencies:
    - compile

# 64-bit linux portable builds
package-linux-amd64:
  stage: package
  tags:
    - linux
  script:
    - release/ci-package.js linux amd64
  artifacts:
    expire_in: 1 week
    paths:
      - packages
  dependencies:
    - compile

# macOS .zip
package-darwin-amd64:
  stage: package
  tags:
    - darwin
  script:
    - release/ci-package.js darwin amd64
  artifacts:
    expire_in: 1 week
    paths:
      - packages
  dependencies:
    - compile

# windows 32-bit build
package-windows-386:
  stage: package
  tags:
    - windows
  script:
    - export BUTLER_ENABLE=1
    - release/ci-package.js windows 386
  artifacts:
    expire_in: 1 week
    paths:
      - packages
  dependencies:
    - compile

# windows 64-bit build
package-windows-amd64:
  stage: package
  tags:
    - windows
  script:
    - export BUTLER_ENABLE=1
    - release/ci-package.js windows amd64
  artifacts:
    expire_in: 1 week
    paths:
      - packages
  dependencies:
    - compile

deploy-itchio:
  stage: deploy
  when: manual
  tags:
    - linux
  only:
    - tags
  script:
    - release/ci-deploy.js
  dependencies:
    - package-linux-386
    - package-linux-amd64
    - package-darwin-amd64
    - package-windows-386
    - package-windows-amd64
  
