os: Visual Studio 2015
install:
  - ps: Install-Product node 4.1
  - npm install -g gulp standard babel-eslint
  - npm install
  - pushd app && npm install & popd
  - gulp all
  - pushd spec\chrome && npm install & popd
  - npm install -g electron-prebuilt
test_script:
  - npm test
notifications:
  - provider: Slack
    auth_token:
      secure: /uzHuC3MJVUjpuBHLDx2YvO6TC3e8AktasVjtzQhvZysPhWfrOB4W5GYNIs/EWbQy2K2tcihv33fmNjS+1jUmg==
    channel: git
