install:
  - ps: Install-Product node 4.1
  - npm install -g gulp standard babel-eslint
  - npm install
  - "(cd app && npm install)"
  - gulp all
  - "(cd spec/chrome && npm install)"
  - npm install -g 'electron-prebuilt@itchio/electron-prebuilt#exit-code'
test_script:
  - npm test
notifications:
  - provider: Slack
    auth_token:
      secure: h7YzDs6wW4jQe0B5U9rZshYhLu4bRi+l9+Qd9GrZrMM=
    channel: git
